"use client";
import { ArrowLeft, ArrowRight, Building2, Check, Plus, Sparkles, Trash2, Users } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { motion } from "motion/react";
import { useState } from "react";

type Person = { name:string; email:string; title:string; division:string; accountRole:"manager"|"member"; functionalRole:"manager"|"employee"|"developer"|"legal"; password:string };
const initialPeople: Person[] = [
  { name:"Raka Wijaya", email:"engineering.manager@company.test", title:"Engineering Manager", division:"Engineering", accountRole:"manager", functionalRole:"manager", password:"Welcome123!" },
  { name:"Dimas Nugroho", email:"developer@company.test", title:"Senior Software Engineer", division:"Engineering", accountRole:"member", functionalRole:"developer", password:"Welcome123!" },
];
export function OnboardingWizard() {
  const router=useRouter(); const [step,setStep]=useState(1); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [companyName,setCompanyName]=useState("Northstar Technologies"); const [adminName,setAdminName]=useState("Maya Putri"); const [adminEmail,setAdminEmail]=useState("maya@northstar.test"); const [password,setPassword]=useState("Welcome123!");
  const [divisions,setDivisions]=useState(["Engineering","Legal & Compliance","Customer Support","Operations"]); const [divisionDraft,setDivisionDraft]=useState(""); const [people,setPeople]=useState<Person[]>(initialPeople);
  const updatePerson=(index:number,key:keyof Person,value:string)=>setPeople(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item));
  async function launch(){setBusy(true);setError("");const response=await fetch("/api/onboarding",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({companyName,adminName,adminEmail,password,divisions,people})});const result=await response.json();if(!response.ok){setError(result.error);setBusy(false);return;}router.push("/workspace");router.refresh();}
  return <main className="onboarding-page"><header className="onboarding-top"><Link href="/" className="marketing-brand"><span>A</span><b>Alethia</b></Link><span>Company setup · {step} of 3</span><Link href="/login">Sign in</Link></header>
    <div className="onboarding-layout"><aside><div className="onboarding-kicker"><Sparkles/> CLIENT-READY SETUP</div><h1>{step===1?"Create your knowledge workspace.":step===2?"Mirror how your company works.":"Give every person the right view."}</h1><p>{step===1?"Your organization becomes the secure boundary for people, documents, campaigns and results.":step===2?"Divisions isolate operational knowledge while company-wide policies remain shared.":"Access role controls authority. Functional role shapes content, workflows and AI context."}</p><div className="setup-flow">{["Company & admin","Allowed divisions","People, roles & login"].map((label,i)=><span className={step>=i+1?"done":""} key={label}><i>{step>i+1?<Check/>:i+1}</i>{label}</span>)}</div></aside>
      <motion.section className="onboarding-card" key={step} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}}>
        {step===1&&<><div className="auth-eyebrow"><Building2/> ORGANIZATION</div><h2>Company identity</h2><div className="form-grid"><label>Company name<input value={companyName} onChange={e=>setCompanyName(e.target.value)}/></label><label>Administrator name<input value={adminName} onChange={e=>setAdminName(e.target.value)}/></label><label>Administrator email<input type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)}/></label><label>Create password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div></>}
        {step===2&&<><div className="auth-eyebrow"><Building2/> STRUCTURE</div><h2>Allowed divisions</h2><p>Managers see only people, campaigns and results inside their division. Organization admins retain a company-wide view.</p><div className="division-list">{divisions.map(d=><span key={d}>{d}<button aria-label={`Remove ${d}`} onClick={()=>setDivisions(v=>v.filter(x=>x!==d))}><Trash2/></button></span>)}</div><div className="inline-add"><input placeholder="Add a division" value={divisionDraft} onChange={e=>setDivisionDraft(e.target.value)}/><button onClick={()=>{if(divisionDraft.trim()&&!divisions.includes(divisionDraft.trim()))setDivisions(v=>[...v,divisionDraft.trim()]);setDivisionDraft("")}}><Plus/> Add</button></div></>}
        {step===3&&<><div className="auth-eyebrow"><Users/> PEOPLE & ACCESS</div><h2>Set up the first team</h2><p>These are real login accounts. Give each person a temporary password of at least 8 characters.</p><div className="people-editor">{people.map((person,index)=><div className="person-row" key={index}><input aria-label="Name" placeholder="Full name" value={person.name} onChange={e=>updatePerson(index,"name",e.target.value)}/><input aria-label="Email" type="email" placeholder="Work email" value={person.email} onChange={e=>updatePerson(index,"email",e.target.value)}/><select aria-label="Division" value={person.division} onChange={e=>updatePerson(index,"division",e.target.value)}>{divisions.map(d=><option key={d}>{d}</option>)}</select><select aria-label="Access role" value={person.accountRole} onChange={e=>updatePerson(index,"accountRole",e.target.value)}><option value="manager">Division manager</option><option value="member">Member</option></select><select aria-label="Functional role" value={person.functionalRole} onChange={e=>updatePerson(index,"functionalRole",e.target.value)}><option value="developer">Developer</option><option value="employee">Employee</option><option value="legal">Legal</option><option value="manager">Manager</option></select><input aria-label="Temporary password" type="password" minLength={8} placeholder="Temporary password" value={person.password} onChange={e=>updatePerson(index,"password",e.target.value)}/><button className="remove-person" aria-label={`Remove ${person.name || "person"}`} onClick={()=>setPeople(v=>v.filter((_,i)=>i!==index))}><Trash2/></button></div>)}</div><button className="add-person" onClick={()=>setPeople(v=>[...v,{name:"",email:"",title:"",division:divisions[0],accountRole:"member",functionalRole:"employee",password:""}])}><Plus/> Add person</button><div className="launch-summary"><Sparkles/><span><b>Showcase content included</b>Developer architecture, local setup, delivery and incident docs will be added automatically so your first tour starts with a credible knowledge base.</span></div></>}
        {error&&<div className="login-error">{error}</div>}<footer><button className="btn" onClick={()=>step===1?router.push("/login"):setStep(s=>s-1)}><ArrowLeft/> Back</button><button className="btn primary" onClick={()=>step<3?setStep(s=>s+1):void launch()} disabled={busy||!companyName||!adminEmail||!divisions.length}>{busy?"Creating workspace…":step<3?"Continue":"Launch company workspace"}<ArrowRight/></button></footer>
      </motion.section></div></main>;
}
